name: AI Agent Evaluation

on:
  workflow_call:
  workflow_dispatch:  

permissions:
  contents: read
  id-token: write

env:
  DATA_PATH: "${{ github.workspace }}/.github/.test_files/agent-eval-small.json"

jobs:
  create-math-agent:
    name: Agent Evaluations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure authentication
        run: |
          az account show

      - name: Run evaluation
        uses: microsoft/ai-agent-evals@v2-beta
        with:
          azure-ai-project-endpoint: ${{ secrets.FOUNDRY_PROJECT_ENDPOINT }}
          deployment-name: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}
          data-path: ${{ env.DATA_PATH }}
          agent-ids: ${{ secrets.AGENT_ID }}
          baseline-agent-id: ${{ secrets.AGENT_ID }}

